// Code generated by MockGen. DO NOT EDIT.
// Source: model.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/rycln/gokeep/shared/models"
)

// MockitemGetter is a mock of itemGetter interface.
type MockitemGetter struct {
	ctrl     *gomock.Controller
	recorder *MockitemGetterMockRecorder
}

// MockitemGetterMockRecorder is the mock recorder for MockitemGetter.
type MockitemGetterMockRecorder struct {
	mock *MockitemGetter
}

// NewMockitemGetter creates a new mock instance.
func NewMockitemGetter(ctrl *gomock.Controller) *MockitemGetter {
	mock := &MockitemGetter{ctrl: ctrl}
	mock.recorder = &MockitemGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockitemGetter) EXPECT() *MockitemGetterMockRecorder {
	return m.recorder
}

// GetContent mocks base method.
func (m *MockitemGetter) GetContent(arg0 context.Context, arg1 models.ItemID) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContent", arg0, arg1)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContent indicates an expected call of GetContent.
func (mr *MockitemGetterMockRecorder) GetContent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContent", reflect.TypeOf((*MockitemGetter)(nil).GetContent), arg0, arg1)
}

// List mocks base method.
func (m *MockitemGetter) List(arg0 context.Context, arg1 models.UserID) ([]models.ItemInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]models.ItemInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockitemGetterMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockitemGetter)(nil).List), arg0, arg1)
}

// MockitemDeleter is a mock of itemDeleter interface.
type MockitemDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockitemDeleterMockRecorder
}

// MockitemDeleterMockRecorder is the mock recorder for MockitemDeleter.
type MockitemDeleterMockRecorder struct {
	mock *MockitemDeleter
}

// NewMockitemDeleter creates a new mock instance.
func NewMockitemDeleter(ctrl *gomock.Controller) *MockitemDeleter {
	mock := &MockitemDeleter{ctrl: ctrl}
	mock.recorder = &MockitemDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockitemDeleter) EXPECT() *MockitemDeleterMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockitemDeleter) Delete(arg0 context.Context, arg1 models.ItemID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockitemDeleterMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockitemDeleter)(nil).Delete), arg0, arg1)
}

// MockitemService is a mock of itemService interface.
type MockitemService struct {
	ctrl     *gomock.Controller
	recorder *MockitemServiceMockRecorder
}

// MockitemServiceMockRecorder is the mock recorder for MockitemService.
type MockitemServiceMockRecorder struct {
	mock *MockitemService
}

// NewMockitemService creates a new mock instance.
func NewMockitemService(ctrl *gomock.Controller) *MockitemService {
	mock := &MockitemService{ctrl: ctrl}
	mock.recorder = &MockitemServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockitemService) EXPECT() *MockitemServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockitemService) Delete(arg0 context.Context, arg1 models.ItemID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockitemServiceMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockitemService)(nil).Delete), arg0, arg1)
}

// GetContent mocks base method.
func (m *MockitemService) GetContent(arg0 context.Context, arg1 models.ItemID) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContent", arg0, arg1)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContent indicates an expected call of GetContent.
func (mr *MockitemServiceMockRecorder) GetContent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContent", reflect.TypeOf((*MockitemService)(nil).GetContent), arg0, arg1)
}

// List mocks base method.
func (m *MockitemService) List(arg0 context.Context, arg1 models.UserID) ([]models.ItemInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]models.ItemInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockitemServiceMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockitemService)(nil).List), arg0, arg1)
}

// MocksyncService is a mock of syncService interface.
type MocksyncService struct {
	ctrl     *gomock.Controller
	recorder *MocksyncServiceMockRecorder
}

// MocksyncServiceMockRecorder is the mock recorder for MocksyncService.
type MocksyncServiceMockRecorder struct {
	mock *MocksyncService
}

// NewMocksyncService creates a new mock instance.
func NewMocksyncService(ctrl *gomock.Controller) *MocksyncService {
	mock := &MocksyncService{ctrl: ctrl}
	mock.recorder = &MocksyncServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksyncService) EXPECT() *MocksyncServiceMockRecorder {
	return m.recorder
}

// SyncUserItems mocks base method.
func (m *MocksyncService) SyncUserItems(arg0 context.Context, arg1 *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncUserItems", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncUserItems indicates an expected call of SyncUserItems.
func (mr *MocksyncServiceMockRecorder) SyncUserItems(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncUserItems", reflect.TypeOf((*MocksyncService)(nil).SyncUserItems), arg0, arg1)
}
