// Code generated by MockGen. DO NOT EDIT.
// Source: userhandler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/rycln/gokeep/shared/models"
)

// MockuserService is a mock of userService interface.
type MockuserService struct {
	ctrl     *gomock.Controller
	recorder *MockuserServiceMockRecorder
}

// MockuserServiceMockRecorder is the mock recorder for MockuserService.
type MockuserServiceMockRecorder struct {
	mock *MockuserService
}

// NewMockuserService creates a new mock instance.
func NewMockuserService(ctrl *gomock.Controller) *MockuserService {
	mock := &MockuserService{ctrl: ctrl}
	mock.recorder = &MockuserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserService) EXPECT() *MockuserServiceMockRecorder {
	return m.recorder
}

// AuthUser mocks base method.
func (m *MockuserService) AuthUser(arg0 context.Context, arg1 *models.UserLoginReq) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthUser", arg0, arg1)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthUser indicates an expected call of AuthUser.
func (mr *MockuserServiceMockRecorder) AuthUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthUser", reflect.TypeOf((*MockuserService)(nil).AuthUser), arg0, arg1)
}

// CreateUser mocks base method.
func (m *MockuserService) CreateUser(arg0 context.Context, arg1 *models.UserRegReq) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockuserServiceMockRecorder) CreateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockuserService)(nil).CreateUser), arg0, arg1)
}

// MockauthProvider is a mock of authProvider interface.
type MockauthProvider struct {
	ctrl     *gomock.Controller
	recorder *MockauthProviderMockRecorder
}

// MockauthProviderMockRecorder is the mock recorder for MockauthProvider.
type MockauthProviderMockRecorder struct {
	mock *MockauthProvider
}

// NewMockauthProvider creates a new mock instance.
func NewMockauthProvider(ctrl *gomock.Controller) *MockauthProvider {
	mock := &MockauthProvider{ctrl: ctrl}
	mock.recorder = &MockauthProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthProvider) EXPECT() *MockauthProviderMockRecorder {
	return m.recorder
}

// AuthFunc mocks base method.
func (m *MockauthProvider) AuthFunc(arg0 context.Context) (context.Context, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthFunc", arg0)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthFunc indicates an expected call of AuthFunc.
func (mr *MockauthProviderMockRecorder) AuthFunc(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthFunc", reflect.TypeOf((*MockauthProvider)(nil).AuthFunc), arg0)
}
