// Code generated by MockGen. DO NOT EDIT.
// Source: synchandler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/rycln/gokeep/shared/models"
)

// MocksyncService is a mock of syncService interface.
type MocksyncService struct {
	ctrl     *gomock.Controller
	recorder *MocksyncServiceMockRecorder
}

// MocksyncServiceMockRecorder is the mock recorder for MocksyncService.
type MocksyncServiceMockRecorder struct {
	mock *MocksyncService
}

// NewMocksyncService creates a new mock instance.
func NewMocksyncService(ctrl *gomock.Controller) *MocksyncService {
	mock := &MocksyncService{ctrl: ctrl}
	mock.recorder = &MocksyncServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksyncService) EXPECT() *MocksyncServiceMockRecorder {
	return m.recorder
}

// SyncItems mocks base method.
func (m *MocksyncService) SyncItems(arg0 context.Context, arg1 []models.Item) ([]models.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncItems", arg0, arg1)
	ret0, _ := ret[0].([]models.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncItems indicates an expected call of SyncItems.
func (mr *MocksyncServiceMockRecorder) SyncItems(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncItems", reflect.TypeOf((*MocksyncService)(nil).SyncItems), arg0, arg1)
}
