// Code generated by MockGen. DO NOT EDIT.
// Source: auth.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/rycln/gokeep/shared/models"
)

// MockjwtServicer is a mock of jwtServicer interface.
type MockjwtServicer struct {
	ctrl     *gomock.Controller
	recorder *MockjwtServicerMockRecorder
}

// MockjwtServicerMockRecorder is the mock recorder for MockjwtServicer.
type MockjwtServicerMockRecorder struct {
	mock *MockjwtServicer
}

// NewMockjwtServicer creates a new mock instance.
func NewMockjwtServicer(ctrl *gomock.Controller) *MockjwtServicer {
	mock := &MockjwtServicer{ctrl: ctrl}
	mock.recorder = &MockjwtServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockjwtServicer) EXPECT() *MockjwtServicerMockRecorder {
	return m.recorder
}

// ParseIDFromJWT mocks base method.
func (m *MockjwtServicer) ParseIDFromJWT(arg0 string) (models.UserID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseIDFromJWT", arg0)
	ret0, _ := ret[0].(models.UserID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseIDFromJWT indicates an expected call of ParseIDFromJWT.
func (mr *MockjwtServicerMockRecorder) ParseIDFromJWT(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseIDFromJWT", reflect.TypeOf((*MockjwtServicer)(nil).ParseIDFromJWT), arg0)
}
