// Code generated by MockGen. DO NOT EDIT.
// Source: syncservice.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/rycln/gokeep/shared/models"
)

// MockitemFetcher is a mock of itemFetcher interface.
type MockitemFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockitemFetcherMockRecorder
}

// MockitemFetcherMockRecorder is the mock recorder for MockitemFetcher.
type MockitemFetcherMockRecorder struct {
	mock *MockitemFetcher
}

// NewMockitemFetcher creates a new mock instance.
func NewMockitemFetcher(ctrl *gomock.Controller) *MockitemFetcher {
	mock := &MockitemFetcher{ctrl: ctrl}
	mock.recorder = &MockitemFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockitemFetcher) EXPECT() *MockitemFetcherMockRecorder {
	return m.recorder
}

// GetUserItems mocks base method.
func (m *MockitemFetcher) GetUserItems(arg0 context.Context, arg1 models.UserID) ([]models.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserItems", arg0, arg1)
	ret0, _ := ret[0].([]models.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserItems indicates an expected call of GetUserItems.
func (mr *MockitemFetcherMockRecorder) GetUserItems(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserItems", reflect.TypeOf((*MockitemFetcher)(nil).GetUserItems), arg0, arg1)
}

// MockitemAdder is a mock of itemAdder interface.
type MockitemAdder struct {
	ctrl     *gomock.Controller
	recorder *MockitemAdderMockRecorder
}

// MockitemAdderMockRecorder is the mock recorder for MockitemAdder.
type MockitemAdderMockRecorder struct {
	mock *MockitemAdder
}

// NewMockitemAdder creates a new mock instance.
func NewMockitemAdder(ctrl *gomock.Controller) *MockitemAdder {
	mock := &MockitemAdder{ctrl: ctrl}
	mock.recorder = &MockitemAdderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockitemAdder) EXPECT() *MockitemAdderMockRecorder {
	return m.recorder
}

// AddItem mocks base method.
func (m *MockitemAdder) AddItem(arg0 context.Context, arg1 *models.Item) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItem", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddItem indicates an expected call of AddItem.
func (mr *MockitemAdderMockRecorder) AddItem(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItem", reflect.TypeOf((*MockitemAdder)(nil).AddItem), arg0, arg1)
}

// MockitemDeleter is a mock of itemDeleter interface.
type MockitemDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockitemDeleterMockRecorder
}

// MockitemDeleterMockRecorder is the mock recorder for MockitemDeleter.
type MockitemDeleterMockRecorder struct {
	mock *MockitemDeleter
}

// NewMockitemDeleter creates a new mock instance.
func NewMockitemDeleter(ctrl *gomock.Controller) *MockitemDeleter {
	mock := &MockitemDeleter{ctrl: ctrl}
	mock.recorder = &MockitemDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockitemDeleter) EXPECT() *MockitemDeleterMockRecorder {
	return m.recorder
}

// DeleteItem mocks base method.
func (m *MockitemDeleter) DeleteItem(arg0 context.Context, arg1 models.ItemID, arg2 models.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItem", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteItem indicates an expected call of DeleteItem.
func (mr *MockitemDeleterMockRecorder) DeleteItem(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItem", reflect.TypeOf((*MockitemDeleter)(nil).DeleteItem), arg0, arg1, arg2)
}

// MockitemStorage is a mock of itemStorage interface.
type MockitemStorage struct {
	ctrl     *gomock.Controller
	recorder *MockitemStorageMockRecorder
}

// MockitemStorageMockRecorder is the mock recorder for MockitemStorage.
type MockitemStorageMockRecorder struct {
	mock *MockitemStorage
}

// NewMockitemStorage creates a new mock instance.
func NewMockitemStorage(ctrl *gomock.Controller) *MockitemStorage {
	mock := &MockitemStorage{ctrl: ctrl}
	mock.recorder = &MockitemStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockitemStorage) EXPECT() *MockitemStorageMockRecorder {
	return m.recorder
}

// AddItem mocks base method.
func (m *MockitemStorage) AddItem(arg0 context.Context, arg1 *models.Item) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItem", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddItem indicates an expected call of AddItem.
func (mr *MockitemStorageMockRecorder) AddItem(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItem", reflect.TypeOf((*MockitemStorage)(nil).AddItem), arg0, arg1)
}

// DeleteItem mocks base method.
func (m *MockitemStorage) DeleteItem(arg0 context.Context, arg1 models.ItemID, arg2 models.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItem", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteItem indicates an expected call of DeleteItem.
func (mr *MockitemStorageMockRecorder) DeleteItem(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItem", reflect.TypeOf((*MockitemStorage)(nil).DeleteItem), arg0, arg1, arg2)
}

// GetUserItems mocks base method.
func (m *MockitemStorage) GetUserItems(arg0 context.Context, arg1 models.UserID) ([]models.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserItems", arg0, arg1)
	ret0, _ := ret[0].([]models.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserItems indicates an expected call of GetUserItems.
func (mr *MockitemStorageMockRecorder) GetUserItems(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserItems", reflect.TypeOf((*MockitemStorage)(nil).GetUserItems), arg0, arg1)
}

// MockuidFetcher is a mock of uidFetcher interface.
type MockuidFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockuidFetcherMockRecorder
}

// MockuidFetcherMockRecorder is the mock recorder for MockuidFetcher.
type MockuidFetcherMockRecorder struct {
	mock *MockuidFetcher
}

// NewMockuidFetcher creates a new mock instance.
func NewMockuidFetcher(ctrl *gomock.Controller) *MockuidFetcher {
	mock := &MockuidFetcher{ctrl: ctrl}
	mock.recorder = &MockuidFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuidFetcher) EXPECT() *MockuidFetcherMockRecorder {
	return m.recorder
}

// GetUserIDFromCtx mocks base method.
func (m *MockuidFetcher) GetUserIDFromCtx(arg0 context.Context) (models.UserID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDFromCtx", arg0)
	ret0, _ := ret[0].(models.UserID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIDFromCtx indicates an expected call of GetUserIDFromCtx.
func (mr *MockuidFetcherMockRecorder) GetUserIDFromCtx(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDFromCtx", reflect.TypeOf((*MockuidFetcher)(nil).GetUserIDFromCtx), arg0)
}
