// Code generated by MockGen. DO NOT EDIT.
// Source: userservice.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/rycln/gokeep/shared/models"
)

// MockuserStorager is a mock of userStorager interface.
type MockuserStorager struct {
	ctrl     *gomock.Controller
	recorder *MockuserStoragerMockRecorder
}

// MockuserStoragerMockRecorder is the mock recorder for MockuserStorager.
type MockuserStoragerMockRecorder struct {
	mock *MockuserStorager
}

// NewMockuserStorager creates a new mock instance.
func NewMockuserStorager(ctrl *gomock.Controller) *MockuserStorager {
	mock := &MockuserStorager{ctrl: ctrl}
	mock.recorder = &MockuserStoragerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserStorager) EXPECT() *MockuserStoragerMockRecorder {
	return m.recorder
}

// AddUser mocks base method.
func (m *MockuserStorager) AddUser(arg0 context.Context, arg1 *models.UserDB) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUser indicates an expected call of AddUser.
func (mr *MockuserStoragerMockRecorder) AddUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockuserStorager)(nil).AddUser), arg0, arg1)
}

// GetUserByUsername mocks base method.
func (m *MockuserStorager) GetUserByUsername(arg0 context.Context, arg1 string) (*models.UserDB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", arg0, arg1)
	ret0, _ := ret[0].(*models.UserDB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockuserStoragerMockRecorder) GetUserByUsername(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockuserStorager)(nil).GetUserByUsername), arg0, arg1)
}

// MockpassHasher is a mock of passHasher interface.
type MockpassHasher struct {
	ctrl     *gomock.Controller
	recorder *MockpassHasherMockRecorder
}

// MockpassHasherMockRecorder is the mock recorder for MockpassHasher.
type MockpassHasherMockRecorder struct {
	mock *MockpassHasher
}

// NewMockpassHasher creates a new mock instance.
func NewMockpassHasher(ctrl *gomock.Controller) *MockpassHasher {
	mock := &MockpassHasher{ctrl: ctrl}
	mock.recorder = &MockpassHasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpassHasher) EXPECT() *MockpassHasherMockRecorder {
	return m.recorder
}

// Compare mocks base method.
func (m *MockpassHasher) Compare(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compare", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Compare indicates an expected call of Compare.
func (mr *MockpassHasherMockRecorder) Compare(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compare", reflect.TypeOf((*MockpassHasher)(nil).Compare), arg0, arg1)
}

// Hash mocks base method.
func (m *MockpassHasher) Hash(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hash indicates an expected call of Hash.
func (mr *MockpassHasherMockRecorder) Hash(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockpassHasher)(nil).Hash), arg0)
}

// MockjwtService is a mock of jwtService interface.
type MockjwtService struct {
	ctrl     *gomock.Controller
	recorder *MockjwtServiceMockRecorder
}

// MockjwtServiceMockRecorder is the mock recorder for MockjwtService.
type MockjwtServiceMockRecorder struct {
	mock *MockjwtService
}

// NewMockjwtService creates a new mock instance.
func NewMockjwtService(ctrl *gomock.Controller) *MockjwtService {
	mock := &MockjwtService{ctrl: ctrl}
	mock.recorder = &MockjwtServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockjwtService) EXPECT() *MockjwtServiceMockRecorder {
	return m.recorder
}

// NewJWTString mocks base method.
func (m *MockjwtService) NewJWTString(arg0 models.UserID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewJWTString", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewJWTString indicates an expected call of NewJWTString.
func (mr *MockjwtServiceMockRecorder) NewJWTString(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewJWTString", reflect.TypeOf((*MockjwtService)(nil).NewJWTString), arg0)
}
