// Code generated by MockGen. DO NOT EDIT.
// Source: userservice.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/rycln/gokeep/shared/models"
)

// MockuserStorage is a mock of userStorage interface.
type MockuserStorage struct {
	ctrl     *gomock.Controller
	recorder *MockuserStorageMockRecorder
}

// MockuserStorageMockRecorder is the mock recorder for MockuserStorage.
type MockuserStorageMockRecorder struct {
	mock *MockuserStorage
}

// NewMockuserStorage creates a new mock instance.
func NewMockuserStorage(ctrl *gomock.Controller) *MockuserStorage {
	mock := &MockuserStorage{ctrl: ctrl}
	mock.recorder = &MockuserStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserStorage) EXPECT() *MockuserStorageMockRecorder {
	return m.recorder
}

// AddUser mocks base method.
func (m *MockuserStorage) AddUser(arg0 context.Context, arg1 *models.UserDB) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUser indicates an expected call of AddUser.
func (mr *MockuserStorageMockRecorder) AddUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockuserStorage)(nil).AddUser), arg0, arg1)
}

// GetUserByUsername mocks base method.
func (m *MockuserStorage) GetUserByUsername(arg0 context.Context, arg1 string) (*models.UserDB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", arg0, arg1)
	ret0, _ := ret[0].(*models.UserDB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockuserStorageMockRecorder) GetUserByUsername(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockuserStorage)(nil).GetUserByUsername), arg0, arg1)
}

// MockpassHasher is a mock of passHasher interface.
type MockpassHasher struct {
	ctrl     *gomock.Controller
	recorder *MockpassHasherMockRecorder
}

// MockpassHasherMockRecorder is the mock recorder for MockpassHasher.
type MockpassHasherMockRecorder struct {
	mock *MockpassHasher
}

// NewMockpassHasher creates a new mock instance.
func NewMockpassHasher(ctrl *gomock.Controller) *MockpassHasher {
	mock := &MockpassHasher{ctrl: ctrl}
	mock.recorder = &MockpassHasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpassHasher) EXPECT() *MockpassHasherMockRecorder {
	return m.recorder
}

// Compare mocks base method.
func (m *MockpassHasher) Compare(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compare", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Compare indicates an expected call of Compare.
func (mr *MockpassHasherMockRecorder) Compare(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compare", reflect.TypeOf((*MockpassHasher)(nil).Compare), arg0, arg1)
}

// Hash mocks base method.
func (m *MockpassHasher) Hash(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hash indicates an expected call of Hash.
func (mr *MockpassHasherMockRecorder) Hash(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockpassHasher)(nil).Hash), arg0)
}

// MockjwtCreator is a mock of jwtCreator interface.
type MockjwtCreator struct {
	ctrl     *gomock.Controller
	recorder *MockjwtCreatorMockRecorder
}

// MockjwtCreatorMockRecorder is the mock recorder for MockjwtCreator.
type MockjwtCreatorMockRecorder struct {
	mock *MockjwtCreator
}

// NewMockjwtCreator creates a new mock instance.
func NewMockjwtCreator(ctrl *gomock.Controller) *MockjwtCreator {
	mock := &MockjwtCreator{ctrl: ctrl}
	mock.recorder = &MockjwtCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockjwtCreator) EXPECT() *MockjwtCreatorMockRecorder {
	return m.recorder
}

// NewJWTString mocks base method.
func (m *MockjwtCreator) NewJWTString(arg0 models.UserID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewJWTString", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewJWTString indicates an expected call of NewJWTString.
func (mr *MockjwtCreatorMockRecorder) NewJWTString(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewJWTString", reflect.TypeOf((*MockjwtCreator)(nil).NewJWTString), arg0)
}
