// Code generated by MockGen. DO NOT EDIT.
// Source: userservice.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/rycln/gokeep/shared/models"
)

// MockAuthAPI is a mock of AuthAPI interface.
type MockAuthAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAuthAPIMockRecorder
}

// MockAuthAPIMockRecorder is the mock recorder for MockAuthAPI.
type MockAuthAPIMockRecorder struct {
	mock *MockAuthAPI
}

// NewMockAuthAPI creates a new mock instance.
func NewMockAuthAPI(ctrl *gomock.Controller) *MockAuthAPI {
	mock := &MockAuthAPI{ctrl: ctrl}
	mock.recorder = &MockAuthAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthAPI) EXPECT() *MockAuthAPIMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAuthAPI) Login(arg0 context.Context, arg1 *models.UserAuthReq) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", arg0, arg1)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthAPIMockRecorder) Login(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthAPI)(nil).Login), arg0, arg1)
}

// Register mocks base method.
func (m *MockAuthAPI) Register(arg0 context.Context, arg1 *models.UserAuthReq) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", arg0, arg1)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockAuthAPIMockRecorder) Register(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthAPI)(nil).Register), arg0, arg1)
}
