// Code generated by MockGen. DO NOT EDIT.
// Source: itemservice.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/rycln/gokeep/shared/models"
)

// MockitemStorer is a mock of itemStorer interface.
type MockitemStorer struct {
	ctrl     *gomock.Controller
	recorder *MockitemStorerMockRecorder
}

// MockitemStorerMockRecorder is the mock recorder for MockitemStorer.
type MockitemStorerMockRecorder struct {
	mock *MockitemStorer
}

// NewMockitemStorer creates a new mock instance.
func NewMockitemStorer(ctrl *gomock.Controller) *MockitemStorer {
	mock := &MockitemStorer{ctrl: ctrl}
	mock.recorder = &MockitemStorerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockitemStorer) EXPECT() *MockitemStorerMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockitemStorer) Add(arg0 context.Context, arg1 *models.ItemInfo, arg2 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockitemStorerMockRecorder) Add(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockitemStorer)(nil).Add), arg0, arg1, arg2)
}

// MockitemGetter is a mock of itemGetter interface.
type MockitemGetter struct {
	ctrl     *gomock.Controller
	recorder *MockitemGetterMockRecorder
}

// MockitemGetterMockRecorder is the mock recorder for MockitemGetter.
type MockitemGetterMockRecorder struct {
	mock *MockitemGetter
}

// NewMockitemGetter creates a new mock instance.
func NewMockitemGetter(ctrl *gomock.Controller) *MockitemGetter {
	mock := &MockitemGetter{ctrl: ctrl}
	mock.recorder = &MockitemGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockitemGetter) EXPECT() *MockitemGetterMockRecorder {
	return m.recorder
}

// GetContent mocks base method.
func (m *MockitemGetter) GetContent(arg0 context.Context, arg1 models.ItemID) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContent", arg0, arg1)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContent indicates an expected call of GetContent.
func (mr *MockitemGetterMockRecorder) GetContent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContent", reflect.TypeOf((*MockitemGetter)(nil).GetContent), arg0, arg1)
}

// ListByUser mocks base method.
func (m *MockitemGetter) ListByUser(arg0 context.Context, arg1 models.UserID) ([]models.ItemInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", arg0, arg1)
	ret0, _ := ret[0].([]models.ItemInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockitemGetterMockRecorder) ListByUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockitemGetter)(nil).ListByUser), arg0, arg1)
}

// MockitemDeleter is a mock of itemDeleter interface.
type MockitemDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockitemDeleterMockRecorder
}

// MockitemDeleterMockRecorder is the mock recorder for MockitemDeleter.
type MockitemDeleterMockRecorder struct {
	mock *MockitemDeleter
}

// NewMockitemDeleter creates a new mock instance.
func NewMockitemDeleter(ctrl *gomock.Controller) *MockitemDeleter {
	mock := &MockitemDeleter{ctrl: ctrl}
	mock.recorder = &MockitemDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockitemDeleter) EXPECT() *MockitemDeleterMockRecorder {
	return m.recorder
}

// DeleteItem mocks base method.
func (m *MockitemDeleter) DeleteItem(arg0 context.Context, arg1 models.ItemID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItem", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteItem indicates an expected call of DeleteItem.
func (mr *MockitemDeleterMockRecorder) DeleteItem(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItem", reflect.TypeOf((*MockitemDeleter)(nil).DeleteItem), arg0, arg1)
}

// MockitemUpdater is a mock of itemUpdater interface.
type MockitemUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockitemUpdaterMockRecorder
}

// MockitemUpdaterMockRecorder is the mock recorder for MockitemUpdater.
type MockitemUpdaterMockRecorder struct {
	mock *MockitemUpdater
}

// NewMockitemUpdater creates a new mock instance.
func NewMockitemUpdater(ctrl *gomock.Controller) *MockitemUpdater {
	mock := &MockitemUpdater{ctrl: ctrl}
	mock.recorder = &MockitemUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockitemUpdater) EXPECT() *MockitemUpdaterMockRecorder {
	return m.recorder
}

// UpdateItem mocks base method.
func (m *MockitemUpdater) UpdateItem(arg0 context.Context, arg1 *models.ItemInfo, arg2 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItem", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateItem indicates an expected call of UpdateItem.
func (mr *MockitemUpdaterMockRecorder) UpdateItem(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItem", reflect.TypeOf((*MockitemUpdater)(nil).UpdateItem), arg0, arg1, arg2)
}

// Mockcrypter is a mock of crypter interface.
type Mockcrypter struct {
	ctrl     *gomock.Controller
	recorder *MockcrypterMockRecorder
}

// MockcrypterMockRecorder is the mock recorder for Mockcrypter.
type MockcrypterMockRecorder struct {
	mock *Mockcrypter
}

// NewMockcrypter creates a new mock instance.
func NewMockcrypter(ctrl *gomock.Controller) *Mockcrypter {
	mock := &Mockcrypter{ctrl: ctrl}
	mock.recorder = &MockcrypterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockcrypter) EXPECT() *MockcrypterMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *Mockcrypter) Decrypt(arg0 []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockcrypterMockRecorder) Decrypt(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*Mockcrypter)(nil).Decrypt), arg0)
}

// Encrypt mocks base method.
func (m *Mockcrypter) Encrypt(arg0 []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockcrypterMockRecorder) Encrypt(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*Mockcrypter)(nil).Encrypt), arg0)
}

// MockitemStorage is a mock of itemStorage interface.
type MockitemStorage struct {
	ctrl     *gomock.Controller
	recorder *MockitemStorageMockRecorder
}

// MockitemStorageMockRecorder is the mock recorder for MockitemStorage.
type MockitemStorageMockRecorder struct {
	mock *MockitemStorage
}

// NewMockitemStorage creates a new mock instance.
func NewMockitemStorage(ctrl *gomock.Controller) *MockitemStorage {
	mock := &MockitemStorage{ctrl: ctrl}
	mock.recorder = &MockitemStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockitemStorage) EXPECT() *MockitemStorageMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockitemStorage) Add(arg0 context.Context, arg1 *models.ItemInfo, arg2 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockitemStorageMockRecorder) Add(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockitemStorage)(nil).Add), arg0, arg1, arg2)
}

// DeleteItem mocks base method.
func (m *MockitemStorage) DeleteItem(arg0 context.Context, arg1 models.ItemID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItem", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteItem indicates an expected call of DeleteItem.
func (mr *MockitemStorageMockRecorder) DeleteItem(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItem", reflect.TypeOf((*MockitemStorage)(nil).DeleteItem), arg0, arg1)
}

// GetContent mocks base method.
func (m *MockitemStorage) GetContent(arg0 context.Context, arg1 models.ItemID) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContent", arg0, arg1)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContent indicates an expected call of GetContent.
func (mr *MockitemStorageMockRecorder) GetContent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContent", reflect.TypeOf((*MockitemStorage)(nil).GetContent), arg0, arg1)
}

// ListByUser mocks base method.
func (m *MockitemStorage) ListByUser(arg0 context.Context, arg1 models.UserID) ([]models.ItemInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", arg0, arg1)
	ret0, _ := ret[0].([]models.ItemInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockitemStorageMockRecorder) ListByUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockitemStorage)(nil).ListByUser), arg0, arg1)
}

// UpdateItem mocks base method.
func (m *MockitemStorage) UpdateItem(arg0 context.Context, arg1 *models.ItemInfo, arg2 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItem", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateItem indicates an expected call of UpdateItem.
func (mr *MockitemStorageMockRecorder) UpdateItem(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItem", reflect.TypeOf((*MockitemStorage)(nil).UpdateItem), arg0, arg1, arg2)
}
