// Code generated by MockGen. DO NOT EDIT.
// Source: userservice.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/rycln/gokeep/shared/models"
)

// MockauthAPI is a mock of authAPI interface.
type MockauthAPI struct {
	ctrl     *gomock.Controller
	recorder *MockauthAPIMockRecorder
}

// MockauthAPIMockRecorder is the mock recorder for MockauthAPI.
type MockauthAPIMockRecorder struct {
	mock *MockauthAPI
}

// NewMockauthAPI creates a new mock instance.
func NewMockauthAPI(ctrl *gomock.Controller) *MockauthAPI {
	mock := &MockauthAPI{ctrl: ctrl}
	mock.recorder = &MockauthAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthAPI) EXPECT() *MockauthAPIMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockauthAPI) Login(arg0 context.Context, arg1 *models.UserLoginReq) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", arg0, arg1)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockauthAPIMockRecorder) Login(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockauthAPI)(nil).Login), arg0, arg1)
}

// Register mocks base method.
func (m *MockauthAPI) Register(arg0 context.Context, arg1 *models.UserRegReq) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", arg0, arg1)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockauthAPIMockRecorder) Register(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockauthAPI)(nil).Register), arg0, arg1)
}
