// Code generated by MockGen. DO NOT EDIT.
// Source: syncservice.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/rycln/gokeep/shared/models"
)

// MocksyncAPI is a mock of syncAPI interface.
type MocksyncAPI struct {
	ctrl     *gomock.Controller
	recorder *MocksyncAPIMockRecorder
}

// MocksyncAPIMockRecorder is the mock recorder for MocksyncAPI.
type MocksyncAPIMockRecorder struct {
	mock *MocksyncAPI
}

// NewMocksyncAPI creates a new mock instance.
func NewMocksyncAPI(ctrl *gomock.Controller) *MocksyncAPI {
	mock := &MocksyncAPI{ctrl: ctrl}
	mock.recorder = &MocksyncAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksyncAPI) EXPECT() *MocksyncAPIMockRecorder {
	return m.recorder
}

// Sync mocks base method.
func (m *MocksyncAPI) Sync(arg0 context.Context, arg1 []models.Item, arg2 string) ([]models.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", arg0, arg1, arg2)
	ret0, _ := ret[0].([]models.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sync indicates an expected call of Sync.
func (mr *MocksyncAPIMockRecorder) Sync(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MocksyncAPI)(nil).Sync), arg0, arg1, arg2)
}

// MocksyncStorage is a mock of syncStorage interface.
type MocksyncStorage struct {
	ctrl     *gomock.Controller
	recorder *MocksyncStorageMockRecorder
}

// MocksyncStorageMockRecorder is the mock recorder for MocksyncStorage.
type MocksyncStorageMockRecorder struct {
	mock *MocksyncStorage
}

// NewMocksyncStorage creates a new mock instance.
func NewMocksyncStorage(ctrl *gomock.Controller) *MocksyncStorage {
	mock := &MocksyncStorage{ctrl: ctrl}
	mock.recorder = &MocksyncStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksyncStorage) EXPECT() *MocksyncStorageMockRecorder {
	return m.recorder
}

// GetAllUserItems mocks base method.
func (m *MocksyncStorage) GetAllUserItems(arg0 context.Context, arg1 models.UserID) ([]models.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUserItems", arg0, arg1)
	ret0, _ := ret[0].([]models.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUserItems indicates an expected call of GetAllUserItems.
func (mr *MocksyncStorageMockRecorder) GetAllUserItems(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUserItems", reflect.TypeOf((*MocksyncStorage)(nil).GetAllUserItems), arg0, arg1)
}

// ReplaceAllUserItems mocks base method.
func (m *MocksyncStorage) ReplaceAllUserItems(arg0 context.Context, arg1 models.UserID, arg2 []models.Item) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceAllUserItems", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceAllUserItems indicates an expected call of ReplaceAllUserItems.
func (mr *MocksyncStorageMockRecorder) ReplaceAllUserItems(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceAllUserItems", reflect.TypeOf((*MocksyncStorage)(nil).ReplaceAllUserItems), arg0, arg1, arg2)
}
