// Code generated by MockGen. DO NOT EDIT.
// Source: model.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/rycln/gokeep/shared/models"
)

// MockitemAdder is a mock of itemAdder interface.
type MockitemAdder struct {
	ctrl     *gomock.Controller
	recorder *MockitemAdderMockRecorder
}

// MockitemAdderMockRecorder is the mock recorder for MockitemAdder.
type MockitemAdderMockRecorder struct {
	mock *MockitemAdder
}

// NewMockitemAdder creates a new mock instance.
func NewMockitemAdder(ctrl *gomock.Controller) *MockitemAdder {
	mock := &MockitemAdder{ctrl: ctrl}
	mock.recorder = &MockitemAdderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockitemAdder) EXPECT() *MockitemAdderMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockitemAdder) Add(arg0 context.Context, arg1 *models.ItemInfo, arg2 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockitemAdderMockRecorder) Add(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockitemAdder)(nil).Add), arg0, arg1, arg2)
}
