// Code generated by MockGen. DO NOT EDIT.
// Source: model.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/rycln/gokeep/shared/models"
)

// MockitemUpdater is a mock of itemUpdater interface.
type MockitemUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockitemUpdaterMockRecorder
}

// MockitemUpdaterMockRecorder is the mock recorder for MockitemUpdater.
type MockitemUpdaterMockRecorder struct {
	mock *MockitemUpdater
}

// NewMockitemUpdater creates a new mock instance.
func NewMockitemUpdater(ctrl *gomock.Controller) *MockitemUpdater {
	mock := &MockitemUpdater{ctrl: ctrl}
	mock.recorder = &MockitemUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockitemUpdater) EXPECT() *MockitemUpdaterMockRecorder {
	return m.recorder
}

// Update mocks base method.
func (m *MockitemUpdater) Update(arg0 context.Context, arg1 *models.ItemInfo, arg2 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockitemUpdaterMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockitemUpdater)(nil).Update), arg0, arg1, arg2)
}
